name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:  
    runs-on: windows-latest 

    env:
      Solution_Name: ConsoleApp1.sln                        # Replace with your solution name, i.e. MyWpfApp.sln.
     
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: set up .NET 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '4.7.2' 
    - name: Install dependencies
      run: dotnet restore
            
    - name: Build
      run: dotnet build -c Release --no-restore

   
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

   

   




   



 
