name: Build and Deploy .NET Framework App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1        
             
      - name: setup Nuget
        uses: Nuget/setup-nuget@v1.0.5
        
      - name: Restore nuget packages
        run: nuget restore ConsoleApp1.sln

      - name: Build App
        run: msbuild ConsoleApp1/ConsoleApp1.sln
      
   

      
