name: Build  .NET Framework

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.x'

      - name: Restore NuGet packages
        run: nuget restore ConsoleApp1.sln

      - name: Build
        run: msbuild ConsoleApp1.sln /p:Configuration=Release

      - name: Restore NuGet packages
        run: nuget restore ConsoleApp1.sln

      - name: Build
        run: msbuild ConsoleApp1.sln /p:Configuration=Release
