name: Build and Deploy .NET Framework App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET CLI
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.0'  # Choose the appropriate version

      - name: Build App
        run: msbuild MyProject/MyProject.csproj /p:Configuration=Release /t:Package /p:PackageTempRootDir=../myapp

      
