name: .NET Core Build 
on:
  push:
    branches:
      - master 
jobs:
  publish:
    name: build, pack, test & publish
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@main

      - name: Install latest .NET SDK
        uses: ConsoleApp1/setup-latest-dotnet@main

      - name: Restore, Build, test, and pack
        uses: ConsoleApp1/build-dotnet@main
        
