name: Build .NET Framework

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
